import { ToolParamsTypeEnum } from '@/constants';
import { VarStatusEnum, type VarType } from '../Workflow/NewGraph/constants';

export const mockVarList: VarType[] = [
  {
    id: 'var-001',
    name: 'user_id',
    desc: '当前会话用户的唯一标识符，用于查询用户信息和订单记录',
    type: ToolParamsTypeEnum.string,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-002',
    name: 'order_id',
    desc: '当前处理中的订单号，在工作流中跨节点传递',
    type: ToolParamsTypeEnum.string,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-003',
    name: 'session_start_time',
    desc: '会话开始时间戳，用于统计会话时长和超时判断',
    type: ToolParamsTypeEnum.integer,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-004',
    name: 'intent_category',
    desc: '用户意图分类标签，由意图识别工具写入，供后续节点路由使用',
    type: ToolParamsTypeEnum.string,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-005',
    name: 'refund_amount',
    desc: '退款核算金额（分），由差价计算工具写入',
    type: ToolParamsTypeEnum.number,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-006',
    name: 'logistics_status',
    desc: '物流当前状态码，由物流查询工具返回并写入',
    type: ToolParamsTypeEnum.string,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-007',
    name: 'member_level',
    desc: '用户会员等级（0-5），用于判断服务优先级和权益范围',
    type: ToolParamsTypeEnum.integer,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-008',
    name: 'is_verified',
    desc: '用户实名认证状态，true=已认证，false=未认证',
    type: ToolParamsTypeEnum.boolean,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-009',
    name: 'product_info',
    desc: '当前处理商品的详细信息对象，包含商品ID、名称、价格等字段',
    type: ToolParamsTypeEnum.object,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-010',
    name: 'selected_tools',
    desc: '用户在当前流程中选择的处理方式列表',
    type: ToolParamsTypeEnum.array,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-011',
    name: 'coupon_code',
    desc: '当前会话中使用的优惠券码，为空则表示未使用优惠券',
    type: ToolParamsTypeEnum.string,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-012',
    name: 'retry_count',
    desc: '当前节点的重试次数，用于控制重试上限和异常兜底逻辑',
    type: ToolParamsTypeEnum.integer,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-013',
    name: 'agent_transfer_reason',
    desc: '转人工原因标签，记录本次转接的触发条件',
    type: ToolParamsTypeEnum.string,
    status: VarStatusEnum.close,
  },
  {
    id: 'var-014',
    name: 'satisfaction_score',
    desc: '用户满意度评分（1-5），由回访节点写入',
    type: ToolParamsTypeEnum.integer,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-015',
    name: 'risk_level',
    desc: '当前会话风控等级（low/medium/high），由风控识别工具写入',
    type: ToolParamsTypeEnum.string,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-016',
    name: 'invoice_info',
    desc: '用户填写的开票信息对象，包含抬头、税号、联系方式等',
    type: ToolParamsTypeEnum.object,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-017',
    name: 'channel_source',
    desc: '用户来源渠道（app/web/mini_program），用于差异化服务策略',
    type: ToolParamsTypeEnum.string,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-018',
    name: 'pending_actions',
    desc: '待执行操作列表，工作流节点间传递需要处理的任务项',
    type: ToolParamsTypeEnum.array,
    status: VarStatusEnum.close,
  },
  {
    id: 'var-019',
    name: 'price_protection_eligible',
    desc: '是否满足价格保护申请条件，由价保核验节点写入',
    type: ToolParamsTypeEnum.boolean,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-020',
    name: 'ticket_id',
    desc: '已创建的客服工单编号，用于后续工单状态查询',
    type: ToolParamsTypeEnum.string,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-021',
    name: 'language_preference',
    desc: '用户语言偏好设置，影响多语言翻译工具的目标语种',
    type: ToolParamsTypeEnum.string,
    status: VarStatusEnum.open,
  },
  {
    id: 'var-022',
    name: 'extra_metadata',
    desc: '扩展元数据对象，存放节点间需要传递的非结构化补充信息',
    type: ToolParamsTypeEnum.object,
    status: VarStatusEnum.close,
  },
];
