import type { AppsNS } from '@/types/Apps';
import { AgentBizTypeEnum, AgentTypeEnum } from '@/constants';

const now = Date.now();
const day = 86400_000;

export const mockAppList: AppsNS.AppType[] = [
  {
    appId: 1001,
    appName: '换货退差助手',
    appDesc: '处理换货重拍后的差价退还问题，自动核算差价并引导客户提交退差申请',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '李晓华',
    updateTime: now - 1 * day,
    prompt: '你是一名专业售后客服，负责处理换货重拍退差价问题',
  },
  {
    appId: 1002,
    appName: '物流查询助手',
    appDesc: '实时查询包裹物流状态，处理物流异常、催单及地址修改等问题',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '王芳',
    updateTime: now - 2 * day,
    prompt: '你是物流客服专员，帮助用户查询快递状态和处理物流问题',
  },
  {
    appId: 1003,
    appName: '退款进度助手',
    appDesc: '查询退款进度，解答退款时效疑问，协助处理退款异常情况',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '李晓华',
    updateTime: now - 3 * day,
  },
  {
    appId: 1004,
    appName: '优惠活动咨询助手',
    appDesc: '解答当前促销活动、优惠券使用规则及满减政策等营销相关问题',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '张明',
    updateTime: now - 3 * day,
    prompt: '你是营销客服，专门解答优惠活动相关问题',
  },
  {
    appId: 1005,
    appName: '商品选购顾问',
    appDesc: '根据用户需求推荐合适商品，提供尺码建议、材质说明及搭配建议',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '王芳',
    updateTime: now - 4 * day,
  },
  {
    appId: 1006,
    appName: '会员积分助手',
    appDesc: '查询会员等级和积分余额，解答积分兑换规则及会员权益相关问题',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '陈静',
    updateTime: now - 5 * day,
    prompt: '你是会员服务专员，负责解答会员积分和权益相关问题',
  },
  {
    appId: 1007,
    appName: '质量问题投诉助手',
    appDesc: '受理商品质量投诉，收集证据并协调售后处理方案，提升客户满意度',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '张明',
    updateTime: now - 6 * day,
  },
  {
    appId: 1008,
    appName: '发票开具助手',
    appDesc: '处理发票申请、修改及重开需求，引导用户完成发票信息填写和提交',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '李晓华',
    updateTime: now - 7 * day,
    prompt: '你是发票服务专员，帮助用户处理发票开具相关问题',
  },
  {
    appId: 1009,
    appName: '预售订单助手',
    appDesc: '解答预售规则、定金支付及尾款时间节点，处理预售订单变更需求',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '陈静',
    updateTime: now - 8 * day,
  },
  {
    appId: 1010,
    appName: '价格保护申请助手',
    appDesc: '受理商品降价后的价格保护申请，自动核算差价并发起补偿流程',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '王芳',
    updateTime: now - 9 * day,
    prompt: '你是价格保护专员，负责处理客户的价格保护申请',
  },
  {
    appId: 1011,
    appName: '海外订单助手',
    appDesc: '处理跨境订单查询、清关问题及关税说明，支持多币种价格换算',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '张明',
    updateTime: now - 10 * day,
  },
  {
    appId: 1012,
    appName: '企业采购助手',
    appDesc: '对接企业批量采购需求，提供报价、合同咨询及专属折扣申请服务',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '刘洋',
    updateTime: now - 11 * day,
    prompt: '你是企业采购专员，服务B端客户的批量采购需求',
  },
  {
    appId: 1013,
    appName: '电器安装预约助手',
    appDesc: '接受家电安装上门预约，确认时间窗口并发送预约确认通知',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '陈静',
    updateTime: now - 12 * day,
  },
  {
    appId: 1014,
    appName: '维修报修助手',
    appDesc: '受理商品维修报修申请，判断保内/保外并引导用户选择维修方式',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '李晓华',
    updateTime: now - 13 * day,
    prompt: '你是售后维修专员，负责处理商品报修和维修跟进',
  },
  {
    appId: 1015,
    appName: '账户安全助手',
    appDesc: '处理账户异常登录提醒、密码修改及支付密码重置等安全类问题',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '王芳',
    updateTime: now - 14 * day,
  },
  {
    appId: 1016,
    appName: '礼品卡使用助手',
    appDesc: '解答礼品卡余额查询、使用限制及有效期问题，处理兑换异常',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '张明',
    updateTime: now - 15 * day,
    prompt: '你是礼品卡服务专员，帮助用户使用和管理礼品卡',
  },
  {
    appId: 1017,
    appName: '新用户引导助手',
    appDesc: '引导新注册用户完成实名认证、首单优惠领取及平台功能介绍',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '刘洋',
    updateTime: now - 16 * day,
  },
  {
    appId: 1018,
    appName: '智能质检助手',
    appDesc: '自动检测客服对话质量，识别违规用语、服务态度及流程合规性',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Inspection,
    updateStaffName: '陈静',
    updateTime: now - 17 * day,
    prompt: '你是智能质检员，负责对客服对话进行质量检测和评分',
  },
  {
    appId: 1019,
    appName: '增值服务推荐助手',
    appDesc: '基于用户购买记录，智能推荐延保服务、清洁护理等增值产品',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '李晓华',
    updateTime: now - 18 * day,
  },
  {
    appId: 1020,
    appName: '节假日专项客服助手',
    appDesc: '应对节假日大促流量，自动处理常见售前售后问题，降低人工压力',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '王芳',
    updateTime: now - 19 * day,
    prompt: '你是节假日专项客服，高效处理大促期间的客户咨询',
  },
  {
    appId: 1021,
    appName: '智能回访机器人',
    appDesc: '对售后完结客户进行满意度回访，收集体验反馈并生成分析报告',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.OutboundRobot,
    updateStaffName: '张明',
    updateTime: now - 20 * day,
  },
  {
    appId: 1022,
    appName: '消费记录查询助手',
    appDesc: '查询历史消费记录、对账单及退款明细，支持按时间段筛选导出',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '刘洋',
    updateTime: now - 21 * day,
    prompt: '你是账单查询专员，帮助用户查询消费记录和账单明细',
  },
  {
    appId: 1023,
    appName: '大客户专属助手',
    appDesc: '为年消费超过10万的大客户提供一对一专属服务，优先响应并提供专属权益',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '陈静',
    updateTime: now - 22 * day,
  },
  {
    appId: 1024,
    appName: 'ERP对接助手',
    appDesc: '对接企业ERP系统，自动同步订单状态、库存信息及发货数据',
    type: AgentTypeEnum.thirdParty,
    bizType: AgentBizTypeEnum.Service,
    updateStaffName: '李晓华',
    updateTime: now - 23 * day,
    prompt: '你负责ERP系统对接，同步企业订单和库存数据',
  },
  {
    appId: 1025,
    appName: '呼入客服智能助手',
    appDesc: '接听客户来电，快速识别意图并给出标准答复，无法处理时转接人工坐席',
    type: AgentTypeEnum.self,
    bizType: AgentBizTypeEnum.CallInRobot,
    updateStaffName: '王芳',
    updateTime: now - 24 * day,
    prompt: '你是呼入智能客服，负责接听电话并处理客户问题',
  },
];
