import type { ToolNS } from '@/types/Tools';
import { AuthTypeEnum, ToolboxTypeEnum } from '@/constants';

const now = Date.now();
const day = 86400_000;

const emptyAuth: ToolNS.AuthConfigType = { authType: AuthTypeEnum.no, appKey: '', secretKey: '' };

export const mockToolboxList: Array<ToolNS.ToolBoxType & {
  updateStaffName: string;
  agentBindCount: number;
  workflowBindCount: number;
  updateTime: number;
  toolNames: string[];
}> = [
  {
    toolboxId: 'mock-tb-001',
    name: '物流查询工具组',
    desc: '提供快递单号查询、物流轨迹追踪、签收状态查询等接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/logistics',
    headers: [],
    toolNames: ['查询物流状态', '获取物流轨迹', '催单接口'],
    agentBindCount: 5,
    workflowBindCount: 2,
    updateStaffName: '李晓华',
    updateTime: now - 1 * day,
  },
  {
    toolboxId: 'mock-tb-002',
    name: '订单管理工具组',
    desc: '订单查询、订单取消、换货申请等电商订单全流程管理接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/order',
    headers: [],
    toolNames: ['查询订单详情', '申请取消订单', '提交换货申请'],
    agentBindCount: 8,
    workflowBindCount: 3,
    updateStaffName: '王芳',
    updateTime: now - 2 * day,
  },
  {
    toolboxId: 'mock-tb-003',
    name: '退款处理工具组',
    desc: '退款申请受理、退款进度查询、退款金额核算等退款全流程接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/refund',
    headers: [],
    toolNames: ['提交退款申请', '查询退款进度', '核算退款金额'],
    agentBindCount: 6,
    workflowBindCount: 1,
    updateStaffName: '张明',
    updateTime: now - 3 * day,
  },
  {
    toolboxId: 'mock-tb-004',
    name: '会员积分工具组',
    desc: '会员等级查询、积分余额查询、积分兑换、积分明细等会员服务接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/member',
    headers: [],
    toolNames: ['查询积分余额', '积分兑换接口', '获取会员等级'],
    agentBindCount: 4,
    workflowBindCount: 0,
    updateStaffName: '陈静',
    updateTime: now - 4 * day,
  },
  {
    toolboxId: 'mock-tb-005',
    name: '商品信息工具组',
    desc: '商品详情查询、库存查询、价格查询、商品推荐等商品相关接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/product',
    headers: [],
    toolNames: ['查询商品详情', '查询库存状态', '获取商品推荐'],
    agentBindCount: 7,
    workflowBindCount: 2,
    updateStaffName: '刘洋',
    updateTime: now - 5 * day,
  },
  {
    toolboxId: 'mock-tb-006',
    name: '优惠券工具组',
    desc: '优惠券领取、优惠券查询、使用规则说明、券码核销等营销接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/coupon',
    headers: [],
    toolNames: ['查询可用优惠券', '核销优惠券', '获取领券资格'],
    agentBindCount: 3,
    workflowBindCount: 1,
    updateStaffName: '李晓华',
    updateTime: now - 6 * day,
  },
  {
    toolboxId: 'mock-tb-007',
    name: '支付工具组',
    desc: '支付状态查询、支付结果回调处理、退款发起等支付流程接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/payment',
    headers: [],
    toolNames: ['查询支付状态', '发起退款', '查询支付方式'],
    agentBindCount: 9,
    workflowBindCount: 4,
    updateStaffName: '王芳',
    updateTime: now - 7 * day,
  },
  {
    toolboxId: 'mock-tb-008',
    name: '发票管理工具组',
    desc: '发票申请、发票信息修改、发票状态查询、电子发票下载等接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/invoice',
    headers: [],
    toolNames: ['申请开票', '修改发票信息', '下载电子发票'],
    agentBindCount: 2,
    workflowBindCount: 0,
    updateStaffName: '张明',
    updateTime: now - 8 * day,
  },
  {
    toolboxId: 'mock-tb-009',
    name: '地址管理工具组',
    desc: '收货地址查询、地址新增修改、地址验证、行政区划查询等接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/address',
    headers: [],
    toolNames: ['获取收货地址', '验证地址格式', '查询行政区划'],
    agentBindCount: 4,
    workflowBindCount: 1,
    updateStaffName: '陈静',
    updateTime: now - 9 * day,
  },
  {
    toolboxId: 'mock-tb-010',
    name: '客服工单工具组',
    desc: '工单创建、工单查询、工单流转、客服转接等客服系统对接接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/ticket',
    headers: [],
    toolNames: ['创建服务工单', '查询工单状态', '转接人工客服'],
    agentBindCount: 11,
    workflowBindCount: 5,
    updateStaffName: '刘洋',
    updateTime: now - 10 * day,
  },
  {
    toolboxId: 'mock-tb-011',
    name: '用户信息工具组',
    desc: '用户基本信息查询、实名认证状态、账号安全信息等用户数据接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/user',
    headers: [],
    toolNames: ['查询用户信息', '验证实名状态', '获取安全等级'],
    agentBindCount: 6,
    workflowBindCount: 2,
    updateStaffName: '李晓华',
    updateTime: now - 11 * day,
  },
  {
    toolboxId: 'mock-tb-012',
    name: '评价工具组',
    desc: '商品评价查询、追评功能、评价内容分析等用户评价相关接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/review',
    headers: [],
    toolNames: ['查询商品评价', '提交评价反馈', '追加评论'],
    agentBindCount: 2,
    workflowBindCount: 0,
    updateStaffName: '王芳',
    updateTime: now - 12 * day,
  },
  {
    toolboxId: 'mock-tb-013',
    name: '消息通知工具组',
    desc: '短信发送、消息推送、邮件通知、站内信发送等通知类接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/notify',
    headers: [],
    toolNames: ['发送短信通知', '推送APP消息', '发送邮件'],
    agentBindCount: 3,
    workflowBindCount: 2,
    updateStaffName: '张明',
    updateTime: now - 13 * day,
  },
  {
    toolboxId: 'mock-tb-014',
    name: '价格保护工具组',
    desc: '价格保护申请、差价核算、补偿发放等价格保护全流程接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/price-protect',
    headers: [],
    toolNames: ['提交价保申请', '核算差价金额', '查询价保资格'],
    agentBindCount: 3,
    workflowBindCount: 1,
    updateStaffName: '陈静',
    updateTime: now - 14 * day,
  },
  {
    toolboxId: 'mock-tb-015',
    name: '预约安装工具组',
    desc: '家电安装上门预约、预约时间查询、预约修改与取消等接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/install',
    headers: [],
    toolNames: ['提交安装预约', '查询预约时间', '修改预约信息'],
    agentBindCount: 2,
    workflowBindCount: 0,
    updateStaffName: '刘洋',
    updateTime: now - 15 * day,
  },
  {
    toolboxId: 'mock-tb-016',
    name: 'ERP数据工具组',
    desc: '对接企业ERP系统，提供订单同步、库存同步、出入库记录查询等接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/erp',
    headers: [],
    toolNames: ['同步ERP订单', '查询库存数据', '获取出入库记录'],
    agentBindCount: 1,
    workflowBindCount: 3,
    updateStaffName: '李晓华',
    updateTime: now - 16 * day,
  },
  {
    toolboxId: 'mock-tb-017',
    name: '风控识别工具组',
    desc: '欺诈行为识别、黑名单查询、异常登录检测等安全风控类接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/risk',
    headers: [],
    toolNames: ['风险行为识别', '查询黑名单', '检测异常登录'],
    agentBindCount: 4,
    workflowBindCount: 2,
    updateStaffName: '王芳',
    updateTime: now - 17 * day,
  },
  {
    toolboxId: 'mock-tb-018',
    name: '知识库搜索工具组',
    desc: '内容语义搜索、FAQ问答匹配、知识文档检索等知识库相关接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/knowledge',
    headers: [],
    toolNames: ['语义搜索', 'FAQ匹配', '文档检索'],
    agentBindCount: 12,
    workflowBindCount: 6,
    updateStaffName: '张明',
    updateTime: now - 18 * day,
  },
  {
    toolboxId: 'mock-tb-019',
    name: '数据统计工具组',
    desc: '客服数据汇总、满意度统计、问题分类统计等数据分析类接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/stats',
    headers: [],
    toolNames: ['获取客服统计', '满意度汇总', '问题热点分析'],
    agentBindCount: 2,
    workflowBindCount: 1,
    updateStaffName: '陈静',
    updateTime: now - 19 * day,
  },
  {
    toolboxId: 'mock-tb-020',
    name: '翻译与识别工具组',
    desc: '多语言文本翻译、图片文字识别(OCR)、语音转文字等AI能力接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/ai-tools',
    headers: [],
    toolNames: ['文本翻译', '图片OCR识别', '语音转文字'],
    agentBindCount: 5,
    workflowBindCount: 3,
    updateStaffName: '刘洋',
    updateTime: now - 20 * day,
  },
  {
    toolboxId: 'mock-tb-021',
    name: '礼品卡工具组',
    desc: '礼品卡余额查询、礼品卡激活、使用记录查询等礼品卡管理接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/gift-card',
    headers: [],
    toolNames: ['查询礼品卡余额', '激活礼品卡', '查询使用记录'],
    agentBindCount: 1,
    workflowBindCount: 0,
    updateStaffName: '李晓华',
    updateTime: now - 21 * day,
  },
  {
    toolboxId: 'mock-tb-022',
    name: '维修服务工具组',
    desc: '报修申请、维修进度查询、保修期判断、维修费用预估等售后维修接口',
    type: ToolboxTypeEnum.custom,
    certification: emptyAuth,
    url: 'https://api.example.com/repair',
    headers: [],
    toolNames: ['提交报修申请', '查询维修进度', '查询保修信息'],
    agentBindCount: 3,
    workflowBindCount: 1,
    updateStaffName: '王芳',
    updateTime: now - 22 * day,
  },
];
