import type { WorkflowNS } from '@/types/Workflow';
import { WorkflowStatusEnum } from '@/constants';

const now = Date.now();
const day = 86400_000;

export const mockWorkflowList: Array<WorkflowNS.WorkflowType & {
  agentBindCount: number;
  workflowRefCount: number;
  isNew: boolean;
}> = [
  {
    workflowId: 3001,
    workflowName: '退换货全流程处理',
    workflowDesc: '从退换货申请受理到最终处理结案的完整自动化工作流',
    status: WorkflowStatusEnum.release,
    updateTime: now - 1 * day,
    releaseTime: now - 1 * day,
    agentBindCount: 3,
    workflowRefCount: 1,
    isNew: true,
  },
  {
    workflowId: 3002,
    workflowName: '物流异常自动处理',
    workflowDesc: '物流超时/丢件/破损等异常情况的自动识别与处理工作流',
    status: WorkflowStatusEnum.release,
    updateTime: now - 2 * day,
    releaseTime: now - 3 * day,
    agentBindCount: 2,
    workflowRefCount: 0,
    isNew: true,
  },
  {
    workflowId: 3003,
    workflowName: '用户身份核验流程',
    workflowDesc: '结合手机验证码与实名信息的双重身份验证工作流',
    status: WorkflowStatusEnum.noRelease,
    updateTime: now - 3 * day,
    releaseTime: undefined,
    agentBindCount: 0,
    workflowRefCount: 0,
    isNew: true,
  },
  {
    workflowId: 3004,
    workflowName: '售后满意度回访',
    workflowDesc: '订单完结后自动触发满意度调研，收集并分类用户反馈',
    status: WorkflowStatusEnum.release,
    updateTime: now - 4 * day,
    releaseTime: now - 4 * day,
    agentBindCount: 1,
    workflowRefCount: 2,
    isNew: true,
  },
  {
    workflowId: 3005,
    workflowName: '价格保护申请审核',
    workflowDesc: '自动核算商品降价差额，审核通过后发起补差价流程',
    status: WorkflowStatusEnum.release,
    updateTime: now - 5 * day,
    releaseTime: now - 6 * day,
    agentBindCount: 2,
    workflowRefCount: 0,
    isNew: true,
  },
  {
    workflowId: 3006,
    workflowName: '优惠活动推送流程',
    workflowDesc: '根据用户标签智能匹配并推送个性化优惠活动',
    status: WorkflowStatusEnum.noRelease,
    updateTime: now - 6 * day,
    releaseTime: undefined,
    agentBindCount: 0,
    workflowRefCount: 1,
    isNew: true,
  },
  {
    workflowId: 3007,
    workflowName: '企业采购审批流程',
    workflowDesc: '企业B端批量采购申请的多级审批与合同生成自动化流程',
    status: WorkflowStatusEnum.release,
    updateTime: now - 7 * day,
    releaseTime: now - 8 * day,
    agentBindCount: 1,
    workflowRefCount: 0,
    isNew: true,
  },
  {
    workflowId: 3008,
    workflowName: '质检任务分配流程',
    workflowDesc: '根据业务优先级和坐席负载自动分配质检任务的工作流',
    status: WorkflowStatusEnum.release,
    updateTime: now - 8 * day,
    releaseTime: now - 9 * day,
    agentBindCount: 4,
    workflowRefCount: 0,
    isNew: true,
  },
  {
    workflowId: 3009,
    workflowName: '工单自动分类路由',
    workflowDesc: '根据客户问题自动识别意图并路由到对应处理队列',
    status: WorkflowStatusEnum.release,
    updateTime: now - 9 * day,
    releaseTime: now - 10 * day,
    agentBindCount: 6,
    workflowRefCount: 2,
    isNew: true,
  },
  {
    workflowId: 3010,
    workflowName: '发票开具流程',
    workflowDesc: '从发票信息收集到开具完成的全自动化发票申请处理工作流',
    status: WorkflowStatusEnum.noRelease,
    updateTime: now - 10 * day,
    releaseTime: undefined,
    agentBindCount: 0,
    workflowRefCount: 0,
    isNew: true,
  },
  {
    workflowId: 3011,
    workflowName: '新用户激活引导',
    workflowDesc: '新注册用户的首次登录引导、实名认证、首单优惠领取自动化流程',
    status: WorkflowStatusEnum.release,
    updateTime: now - 11 * day,
    releaseTime: now - 11 * day,
    agentBindCount: 2,
    workflowRefCount: 1,
    isNew: true,
  },
  {
    workflowId: 3012,
    workflowName: '跨境订单清关通知',
    workflowDesc: '国际订单清关状态监控，异常时自动通知客户并给出处理建议',
    status: WorkflowStatusEnum.release,
    updateTime: now - 12 * day,
    releaseTime: now - 13 * day,
    agentBindCount: 1,
    workflowRefCount: 0,
    isNew: true,
  },
  {
    workflowId: 3013,
    workflowName: '大促备战预案流程',
    workflowDesc: '节假日大促期间客服资源动态调配与预案启动自动化工作流',
    status: WorkflowStatusEnum.noRelease,
    updateTime: now - 13 * day,
    releaseTime: undefined,
    agentBindCount: 0,
    workflowRefCount: 0,
    isNew: true,
  },
  {
    workflowId: 3014,
    workflowName: '信用额度申请审核',
    workflowDesc: '用户信用额度申请的自动化风险评估与审批工作流',
    status: WorkflowStatusEnum.release,
    updateTime: now - 14 * day,
    releaseTime: now - 15 * day,
    agentBindCount: 1,
    workflowRefCount: 2,
    isNew: true,
  },
  {
    workflowId: 3015,
    workflowName: '商品质量投诉处理',
    workflowDesc: '质量投诉受理、责任认定、赔偿方案生成到执行的全流程工作流',
    status: WorkflowStatusEnum.release,
    updateTime: now - 15 * day,
    releaseTime: now - 16 * day,
    agentBindCount: 2,
    workflowRefCount: 0,
    isNew: true,
  },
  {
    workflowId: 3016,
    workflowName: '会员升降级通知',
    workflowDesc: '基于积分变化自动触发会员等级变更，并发送权益变化通知',
    status: WorkflowStatusEnum.release,
    updateTime: now - 16 * day,
    releaseTime: now - 17 * day,
    agentBindCount: 3,
    workflowRefCount: 1,
    isNew: true,
  },
  {
    workflowId: 3017,
    workflowName: '预售订单提醒流程',
    workflowDesc: '预售商品尾款支付提醒、超时处理、发货通知等节点的自动化流程',
    status: WorkflowStatusEnum.noRelease,
    updateTime: now - 17 * day,
    releaseTime: undefined,
    agentBindCount: 0,
    workflowRefCount: 0,
    isNew: true,
  },
  {
    workflowId: 3018,
    workflowName: '增值服务主动推荐',
    workflowDesc: '基于用户购买记录和行为分析的增值服务智能推荐工作流',
    status: WorkflowStatusEnum.release,
    updateTime: now - 18 * day,
    releaseTime: now - 19 * day,
    agentBindCount: 2,
    workflowRefCount: 3,
    isNew: true,
  },
  {
    workflowId: 3019,
    workflowName: '账号异常冻结处理',
    workflowDesc: '检测到账号异常后的自动风险处置、用户通知和申诉受理流程',
    status: WorkflowStatusEnum.release,
    updateTime: now - 19 * day,
    releaseTime: now - 20 * day,
    agentBindCount: 1,
    workflowRefCount: 0,
    isNew: true,
  },
  {
    workflowId: 3020,
    workflowName: '消费账单生成推送',
    workflowDesc: '每月定时生成用户消费账单并通过多渠道推送给用户的工作流',
    status: WorkflowStatusEnum.release,
    updateTime: now - 20 * day,
    releaseTime: now - 21 * day,
    agentBindCount: 2,
    workflowRefCount: 1,
    isNew: true,
  },
  {
    workflowId: 3021,
    workflowName: '维修服务进度同步',
    workflowDesc: '维修状态变更时自动同步给客户，并在完工后发起满意度评价',
    status: WorkflowStatusEnum.noRelease,
    updateTime: now - 21 * day,
    releaseTime: undefined,
    agentBindCount: 0,
    workflowRefCount: 0,
    isNew: true,
  },
  {
    workflowId: 3022,
    workflowName: '黑五跨境促销流程',
    workflowDesc: '针对海外用户的黑五活动关税提示、汇率换算和优惠权益推送',
    status: WorkflowStatusEnum.release,
    updateTime: now - 22 * day,
    releaseTime: now - 23 * day,
    agentBindCount: 1,
    workflowRefCount: 0,
    isNew: true,
  },
];
