import { TestTaskStatus, CountingStatusEnum, type TestTaskType } from './type';

export const mockTestList: TestTaskType[] = [
  {
    id: 5001,
    name: '换货退差助手-基础功能测评',
    agentName: '换货退差助手',
    agentId: 1001,
    taskCount: 100,
    successCount: 100,
    llmCount: 312,
    llmCost: 0.28,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-05-10 10:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5002,
    name: '物流查询助手-意图识别准确率',
    agentName: '物流查询助手',
    agentId: 1002,
    taskCount: 150,
    successCount: 147,
    llmCount: 420,
    llmCost: 0.38,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-05-11 09:30:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5003,
    name: '退款进度助手-边界场景覆盖',
    agentName: '退款进度助手',
    agentId: 1003,
    taskCount: 80,
    successCount: 61,
    llmCount: 289,
    llmCost: 0.22,
    processStatus: TestTaskStatus.running,
    createTime: '2025-05-12 14:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5004,
    name: '会员积分助手-多轮对话测评',
    agentName: '会员积分助手',
    agentId: 1006,
    taskCount: 200,
    successCount: 78,
    llmCount: 156,
    llmCost: 0.14,
    processStatus: TestTaskStatus.stop,
    createTime: '2025-05-13 11:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5005,
    name: '商品选购顾问-推荐准确性测评',
    agentName: '商品选购顾问',
    agentId: 1005,
    taskCount: 120,
    successCount: 120,
    llmCount: 380,
    llmCost: 0.34,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-05-14 09:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5006,
    name: '智能质检助手-检测覆盖率评估',
    agentName: '智能质检助手',
    agentId: 1018,
    taskCount: 300,
    successCount: 300,
    llmCount: 960,
    llmCost: 0.87,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-05-15 10:30:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5007,
    name: '优惠活动咨询助手-知识准确性',
    agentName: '优惠活动咨询助手',
    agentId: 1004,
    taskCount: 90,
    successCount: 0,
    llmCount: 0,
    llmCost: 0,
    processStatus: TestTaskStatus.init,
    createTime: '2025-05-16 16:00:00',
    countingStatus: CountingStatusEnum.counting,
    nosKey: '',
  },
  {
    id: 5008,
    name: '发票开具助手-流程完整性测试',
    agentName: '发票开具助手',
    agentId: 1008,
    taskCount: 60,
    successCount: 57,
    llmCount: 198,
    llmCost: 0.17,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-05-17 09:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5009,
    name: '价格保护申请助手-差价核算准确性',
    agentName: '价格保护申请助手',
    agentId: 1010,
    taskCount: 75,
    successCount: 50,
    llmCount: 100,
    llmCost: 0.09,
    processStatus: TestTaskStatus.running,
    createTime: '2025-05-18 11:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5010,
    name: 'ERP对接助手-数据同步一致性',
    agentName: 'ERP对接助手',
    agentId: 1024,
    taskCount: 50,
    successCount: 50,
    llmCount: 105,
    llmCost: 0.09,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-05-19 09:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5011,
    name: '呼入客服助手-语义理解准确率',
    agentName: '呼入客服智能助手',
    agentId: 1025,
    taskCount: 500,
    successCount: 488,
    llmCount: 1540,
    llmCost: 1.39,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-04-28 10:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5012,
    name: '账户安全助手-风险识别测评',
    agentName: '账户安全助手',
    agentId: 1015,
    taskCount: 180,
    successCount: 0,
    llmCount: 0,
    llmCost: 0,
    processStatus: TestTaskStatus.init,
    createTime: '2025-05-19 14:30:00',
    countingStatus: CountingStatusEnum.counting,
    nosKey: '',
  },
  {
    id: 5013,
    name: '企业采购助手-B端场景覆盖率',
    agentName: '企业采购助手',
    agentId: 1012,
    taskCount: 40,
    successCount: 37,
    llmCount: 122,
    llmCost: 0.11,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-05-01 09:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5014,
    name: '海外订单助手-多币种计算测试',
    agentName: '海外订单助手',
    agentId: 1011,
    taskCount: 65,
    successCount: 30,
    llmCount: 61,
    llmCost: 0.05,
    processStatus: TestTaskStatus.stop,
    createTime: '2025-05-05 15:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5015,
    name: '维修报修助手-保内保外判断准确性',
    agentName: '维修报修助手',
    agentId: 1014,
    taskCount: 55,
    successCount: 55,
    llmCount: 168,
    llmCost: 0.15,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-04-20 10:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5016,
    name: '大客户专属助手-VIP响应策略',
    agentName: '大客户专属助手',
    agentId: 1023,
    taskCount: 30,
    successCount: 30,
    llmCount: 89,
    llmCost: 0.08,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-04-15 11:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5017,
    name: '节假日客服助手-大促场景压测',
    agentName: '节假日专项客服助手',
    agentId: 1020,
    taskCount: 1000,
    successCount: 1000,
    llmCount: 3120,
    llmCost: 2.81,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-04-10 09:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5018,
    name: '消费记录查询助手-数据对账准确性',
    agentName: '消费记录查询助手',
    agentId: 1022,
    taskCount: 85,
    successCount: 82,
    llmCount: 249,
    llmCost: 0.22,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-04-05 10:30:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5019,
    name: '礼品卡使用助手-余额计算测评',
    agentName: '礼品卡使用助手',
    agentId: 1016,
    taskCount: 45,
    successCount: 0,
    llmCount: 0,
    llmCost: 0,
    processStatus: TestTaskStatus.init,
    createTime: '2025-05-19 17:00:00',
    countingStatus: CountingStatusEnum.counting,
    nosKey: '',
  },
  {
    id: 5020,
    name: '新用户引导助手-转化率评估',
    agentName: '新用户引导助手',
    agentId: 1017,
    taskCount: 200,
    successCount: 200,
    llmCount: 620,
    llmCost: 0.56,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-03-25 09:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5021,
    name: '智能回访机器人-话术流畅度测评',
    agentName: '智能回访机器人',
    agentId: 1021,
    taskCount: 120,
    successCount: 115,
    llmCount: 362,
    llmCost: 0.33,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-03-18 14:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
  {
    id: 5022,
    name: '质量投诉助手-解决方案合理性',
    agentName: '质量问题投诉助手',
    agentId: 1007,
    taskCount: 70,
    successCount: 70,
    llmCount: 218,
    llmCost: 0.2,
    processStatus: TestTaskStatus.finish,
    createTime: '2025-03-10 10:00:00',
    countingStatus: CountingStatusEnum.finished,
    nosKey: '',
  },
];
